import { NextResponse } from 'next/server';
import { createServerSupabaseClient } from '@/lib/supabase/server';

// GET /api/cases - Fetch user's cases
export async function GET() {
  const supabase = await createServerSupabaseClient();
  const { data: { user }, error: authError } = await supabase.auth.getUser();

  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { data, error } = await supabase
    .from('client_cases')
    .select('*')
    .eq('user_id', user.id)
    .order('created_at', { ascending: false });

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ cases: data });
}

// POST /api/cases - Create a new case
export async function POST(request: Request) {
  const supabase = await createServerSupabaseClient();
  const { data: { user }, error: authError } = await supabase.auth.getUser();

  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const body = await request.json();
  const { visa_subclass, visa_name, notes } = body as {
    visa_subclass: string; visa_name: string; notes?: string;
  };

  if (!visa_subclass || !visa_name) {
    return NextResponse.json({ error: 'Visa subclass and name are required' }, { status: 400 });
  }

  const { data, error } = await supabase
    .from('client_cases')
    .insert({
      user_id: user.id,
      case_number: '', // auto-generated by trigger
      visa_subclass,
      visa_name,
      notes: notes || null,
    })
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ case: data }, { status: 201 });
}

// PATCH /api/cases - Update case status or details
export async function PATCH(request: Request) {
  const supabase = await createServerSupabaseClient();
  const { data: { user }, error: authError } = await supabase.auth.getUser();

  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const body = await request.json();
  const { id, status, notes, priority } = body as {
    id: string; status?: string; notes?: string; priority?: string;
  };

  if (!id) {
    return NextResponse.json({ error: 'Case ID required' }, { status: 400 });
  }

  const updateData: Record<string, string | null> = {};
  if (status) updateData.status = status;
  if (notes !== undefined) updateData.notes = notes;
  if (priority) updateData.priority = priority;

  const { data, error } = await supabase
    .from('client_cases')
    .update(updateData)
    .eq('id', id)
    .eq('user_id', user.id)
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ case: data });
}
